- set service dhcp-server shared-network-name {{ dhcp_name }} subnet "{{ internal_cidr }}/{{ internal_prefix }}" static-mapping {{ sm_name }} ip-address "{{ CustomVM_ip }}"
- set service dhcp-server shared-network-name {{ dhcp_name }} subnet "{{ internal_cidr }}/{{ internal_prefix }}" static-mapping {{ sm_name }}  mac-address "{{ CustomVM_mac }}"
