- set firewall all-ping 'enable'
- set firewall name {{ firewall_name }} rule {{ firewall_rule }} action '{{ firewall_action }}'
- set firewall name {{ firewall_name }} rule {{ firewall_rule }} protocol '{{ firewall_protocol }}'
