- set service dhcp-server shared-network-name {{ dhcp_name }}
- set service dhcp-server shared-network-name {{ dhcp_name }} authoritative
- set service dhcp-server shared-network-name {{ dhcp_name }} subnet "{{ internal_cidr }}/{{ internal_prefix }}"
- set service dhcp-server shared-network-name {{ dhcp_name }} subnet "{{ internal_cidr }}/{{ internal_prefix }}" default-router "{{ vyos_addr }}"
- set service dhcp-server shared-network-name {{ dhcp_name }} subnet "{{ internal_cidr }}/{{ internal_prefix }}" domain-name google.com
- set service dhcp-server shared-network-name {{ dhcp_name }} subnet "{{ internal_cidr }}/{{ internal_prefix }}" domain-search google.com
- set service dhcp-server shared-network-name {{ dhcp_name }} subnet "{{ internal_cidr }}/{{ internal_prefix }}" range mynet start {{ range_start }}
- set service dhcp-server shared-network-name {{ dhcp_name }} subnet "{{ internal_cidr }}/{{ internal_prefix }}" range mynet stop {{ range_stop }}
